services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    container_name: backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - backend

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - frontend
      - backend
