services:
  backend:
    build:
      context: ./backend
    image: shivam7singh/backend:v1.0
    ports:
      - "4000:4000"
    container_name: backend

  frontend:
    build:
      context: ./frontend
    image: shivam7singh/frontend:v1.0
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
    image: shivam7singh/nginx:v1.0
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
